cambio_nombre_columnas = {
    'CÓDIGO ÓRGÃO SUPERIOR': 'codigo_organo_superior',
    'NOME ÓRGÃO SUPERIOR': 'nombre_organo_superior',
    'CÓDIGO ÓRGÃO': 'codigo_organo',
    'NOME ÓRGÃO': 'nombre_organo',
    'CÓDIGO UNIDADE GESTORA': 'codigo_unidad_gestora',
    'NOME UNIDADE GESTORA': 'nombre_unidad_gestora',
    'CATEGORIA ECONÔMICA': 'categoria_economica',
    'ORIGEM RECEITA': 'origen_ingreso',
    'ESPÉCIE RECEITA': 'tipo_ingreso',
    'DETALHAMENTO': 'detalle',
    'VALOR PREVISTO ATUALIZADO': 'valor_previsto_actualizado',
    'VALOR LANÇADO': 'valor_registrado',
    'VALOR REALIZADO': 'valor_ejecutado',
    'PERCENTUAL REALIZADO': 'porcentaje_ejecutado',
    'DATA LANÇAMENTO': 'fecha_registro',
    'ANO EXERCÍCIO': 'ano_ejercicio'
}

dicc_organo_superior = {63000.0: 'Advocacia-Geral da União',
    37000.0: 'Controladoria-Geral da União',
    22000.0: 'Ministério da Agricultura, Pecuária e Abastec',
    55000.0: 'Ministério da Cidadania',
    24000.0: 'Ministério da Ciência, Tecnologia, Inovações ',
    52000.0: 'Ministério da Defesa',
    25000.0: 'Ministério da Economia',
    26000.0: 'Ministério da Educação',
    39000.0: 'Ministério da Infraestrutura',
    30000.0: 'Ministério da Justiça e Segurança Pública',
    81000.0: 'Ministério da Mulher, Família e Direitos Huma',
    58000.0: 'Ministério da Pesca e Aquicultura',
    33000.0: 'Ministério da Previdência Social',
    36000.0: 'Ministério da Saúde',
    41000.0: 'Ministério das Comunicações',
    57000.0: 'Ministério das Mulheres, Igualdade Racial, da',
    35000.0: 'Ministério das Relações Exteriores',
    32000.0: 'Ministério de Minas e Energia',
    49000.0: 'Ministério do Desenvolvimento Agrário',
    53000.0: 'Ministério do Desenvolvimento Regional',
    51000.0: 'Ministério do Esporte',
    44000.0: 'Ministério do Meio Ambiente',
    38000.0: 'Ministério do Trabalho e Emprego',
    54000.0: 'Ministério do Turismo',
    20000.0: 'Presidência da República'}


dicc_organo = {63000.0: 'Advocacia-Geral da União - Unidades com vínculo direto',
    20402.0: 'Agência Espacial Brasileira',
    62201.0: 'Agência Nacional de Aviação Civil',
    32210.0: 'Agência Nacional de Energia Elétrica',
    32396.0: 'Agência Nacional de Mineração',
    36213.0: 'Agência Nacional de Saúde Suplementar',
    68201.0: 'Agência Nacional de Transportes Aquaviários',
    39251.0: 'Agência Nacional de Transportes Aquaviários',
    39250.0: 'Agência Nacional de Transportes Terrestres',
    36212.0: 'Agência Nacional de Vigilância Sanitária',
    44205.0: 'Agência Nacional de Águas',
    20203.0: 'Agência Nacional do Cinema',
    32205.0: 'Agência Nacional do Petróleo, Gás Natural e Biocombustíveis',
    53205.0: 'Agência de Desenvolvimento da Amazônia',
    41231.0: 'Agêncial Nacional de Telecomunicações',
    52233.0: 'Amazônia Azul Tecnologia de Defesa S.A.',
    91214.0: 'Autoridade Pública Olímpica',
    25201.0: 'Banco Central do Brasil - Orçamento Fiscal e Seguridade Social',
    31280.0: 'Caixa de Construções de Casas para o Pessoal da Marinha do Brasil',
    52211.0: 'Caixa de Financiamento Imobiliário da Aeronáutica',
    25211.0: 'Casa da Moeda do Brasil',
    26256.0: 'Centro Federal de Educação Tecnológica Celso Suckow da Fonseca',
    26257.0: 'Centro Federal de Educação Tecnológica de Minas Gerais',
    24209.0: 'Centro Nacional de Tecnologia Eletrônica Avançada S.A.',
    26201.0: 'Colégio Pedro II',
    52111.0: 'Comando da Aeronáutica',
    52131.0: 'Comando da Marinha',
    52132.0: 'Comando da Marinha - Fundo Naval',
    52121.0: 'Comando do Exército',
    20301.0: 'Comissão Nacional de Energia Nuclear',
    25203.0: 'Comissão de Valores Mobiliários',
    29214.0: 'Companhia Brasileira de Trens Urbanos',
    39813.0: 'Companhia Docas do Ceará',
    39817.0: 'Companhia Docas do Espírito Santo',
    39812.0: 'Companhia Docas do Estado da Bahia',
    39816.0: 'Companhia Docas do Estado de São Paulo',
    39814.0: 'Companhia Docas do Pará',
    39815.0: 'Companhia Docas do Rio Grande do Norte',
    39811.0: 'Companhia Docas do Rio de Janeiro',
    22211.0: 'Companhia Nacional de Abastecimento',
    20605.0: 'Companhia de Desenvolvimento de Barcarena',
    22203.0: 'Companhia de Desenvolvimento dos Vales do São Francisco e do Parnaíba',
    22500.0: 'Companhia de Entrepostos e Armazéns Gerais de São Paulo',
    29208.0: 'Companhia de Pesquisa de Recursos Minerais',
    30211.0: 'Conselho Administrativo de Defesa Econômica',
    20501.0: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico',
    66000.0: 'Controladoria-Geral da União',
    37000.0: 'Controladoria-Geral da União - Unidades com vínculo direto',
    29201.0: 'Departamento Nacional de Estradas de Rodagem',
    39252.0: 'Departamento Nacional de Infraestrutura de Transportes',
    22204.0: 'Departamento Nacional de Obras Contra as Secas',
    32263.0: 'Departamento Nacional de Produção Mineral',
    30108.0: 'Departamento de Polícia Federal',
    30802.0: 'Departamento de Polícia Rodoviária Federal',
    49901.0: 'Departamento do Fundo da Marinha Mercante',
    20415.0: 'Empresa Brasil de Comunicação',
    49280.0: 'Empresa Brasileira de Correios e Telégrafos',
    22202.0: 'Empresa Brasileira de Pesquisa Agropecuária',
    26443.0: 'Empresa Brasileira de Serviços Hospitalares',
    32314.0: 'Empresa de Pesquisa Energética',
    39253.0: 'Empresa de Planejamento e Logística S.A.',
    29205.0: 'Empresa de Trens Urbanos de Porto Alegre',
    20502.0: 'Financiadora de Estudos e Projetos',
    35201.0: 'Fundação Alexandre de Gusmão',
    20404.0: 'Fundação Biblioteca Nacional',
    20403.0: 'Fundação Casa de Rui Barbosa',
    26291.0: 'Fundação Coordenação de Aperfeiçoamento de Pessoal de Nível Superior',
    20408.0: 'Fundação Cultural Palmares',
    20202.0: 'Fundação Escola Nacional de Administração Pública',
    25205.0: 'Fundação Instituto Brasileiro de Geografia e Estatística',
    26292.0: 'Fundação Joaquim Nabuco',
    37201.0: 'Fundação Jorge Duprat Figueiredo, de Segurança e Medicina do Trabalho',
    20412.0: 'Fundação Nacional de Artes',
    36211.0: 'Fundação Nacional de Saúde',
    30202.0: 'Fundação Nacional do Índio',
    30205.0: 'Fundação Nacional do Índio - Patrimônio Indígena',
    36201.0: 'Fundação Oswaldo Cruz',
    52222.0: 'Fundação Osório',
    26350.0: 'Fundação Universidade Federal da Grande Dourados',
    26284.0: 'Fundação Universidade Federal de Ciências da Saúde de Porto Alegre',
    26278.0: 'Fundação Universidade Federal de Pelotas',
    26268.0: 'Fundação Universidade Federal de Rondônia',
    26281.0: 'Fundação Universidade Federal de Sergipe',
    26280.0: 'Fundação Universidade Federal de São Carlos',
    26285.0: 'Fundação Universidade Federal de São João Del-Rei',
    26274.0: 'Fundação Universidade Federal de Uberlândia',
    26352.0: 'Fundação Universidade Federal do ABC',
    26275.0: 'Fundação Universidade Federal do Acre',
    26286.0: 'Fundação Universidade Federal do Amapá',
    26276.0: 'Fundação Universidade Federal do Mato Grosso',
    26283.0: 'Fundação Universidade Federal do Mato Grosso do Sul',
    26266.0: 'Fundação Universidade Federal do Pampa',
    26279.0: 'Fundação Universidade Federal do Piauí',
    26251.0: 'Fundação Universidade Federal do Tocantins',
    26230.0: 'Fundação Universidade Federal do Vale do São Francisco',
    26271.0: 'Fundação Universidade de Brasília',
    26270.0: 'Fundação Universidade do Amazonas',
    26272.0: 'Fundação Universidade do Maranhão',
    52911.0: 'Fundo Aeronáutico',
    52912.0: 'Fundo Aeroviário',
    53902.0: 'Fundo Constitucional de Financiamento do Centro-Oeste',
    53903.0: 'Fundo Constitucional de Financiamento do Nordeste',
    53901.0: 'Fundo Constitucional de Financiamento do Norte',
    25915.0: 'Fundo Constitucional do Distrito Federal',
    25916.0: 'Fundo Contingente da Extinta RFFSA-FCMP',
    54901.0: 'Fundo Geral de Turismo',
    30912.0: 'Fundo Nacional Antidrogas',
    20117.0: 'Fundo Nacional Antidrogas',
    55001.0: 'Fundo Nacional de Assistência Social',
    62901.0: 'Fundo Nacional de Aviação Civil',
    34902.0: 'Fundo Nacional de Cultura',
    20924.0: 'Fundo Nacional de Desenvolvimento',
    24901.0: 'Fundo Nacional de Desenvolvimento Científico e Tecnológico',
    26298.0: 'Fundo Nacional de Desenvolvimento da Educação',
    56902.0: 'Fundo Nacional de Habitação de Interesse Social',
    30911.0: 'Fundo Nacional de Segurança Pública',
    56901.0: 'Fundo Nacional de Segurança e Educação de Trânsito',
    30914.0: 'Fundo Nacional do Idoso',
    64902.0: 'Fundo Nacional do Idoso',
    44204.0: 'Fundo Nacional do Meio Ambiente',
    30913.0: 'Fundo Nacional para a Criança e o Adolescente',
    64901.0: 'Fundo Nacional para a Criança e o Adolescente',
    44902.0: 'Fundo Nacional sobre Mudança no Clima',
    30907.0: 'Fundo Penitenciário Nacional',
    71902.0: 'Fundo Soberano do Brasil',
    38901.0: 'Fundo de Amparo ao Trabalhador',
    25905.0: 'Fundo de Apoio ao Desenvolvimento Social',
    25901.0: 'Fundo de Compensação de Variações Salariais',
    22905.0: 'Fundo de Defesa da Economia Cafeeira',
    74917.0: 'Fundo de Desenvolvimento da Amazônia',
    74919.0: 'Fundo de Desenvolvimento do Centro-Oeste',
    52133.0: 'Fundo de Desenvolvimento do Ensino Profissional Marítimo',
    74918.0: 'Fundo de Desenvolvimento do Nordeste',
    25904.0: 'Fundo de Estabilidade do Seguro Rural',
    28500.0: 'Fundo de Garantia para a Promoção da Competitividade',
    25914.0: 'Fundo de Garantia à Exportação',
    20116.0: 'Fundo de Imprensa Nacional',
    49001.0: 'Fundo de Terras e da Reforma Agrária',
    41232.0: 'Fundo de Universalização dos Serviços de Telecomunicações',
    52904.0: 'Fundo do Exército',
    37904.0: 'Fundo do Regime Geral da Previdência Social',
    41903.0: 'Fundo para o Desenvolvimento Tecnológico das Telecomunicações',
    60000.0: 'Gabinete da Vice-Presidência da República',
    36208.0: 'Hospital Cristo Redentor S.A.',
    36209.0: 'Hospital Fêmina S.A.',
    36210.0: 'Hospital Nossa Senhora da Conceição S.A.',
    26294.0: 'Hospital de Clínicas de Porto Alegre',
    52221.0: 'Indústria de Material Bélico do Brasil',
    20303.0: 'Indústrias Nucleares do Brasil',
    42207.0: 'Instituto Brasileiro de Museus',
    20604.0: 'Instituto Brasileiro de Turismo',
    20701.0: 'Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis',
    44207.0: 'Instituto Chico Mendes de Conservação da Biodiversidade',
    26404.0: 'Instituto Federal Baiano',
    26422.0: 'Instituto Federal Catarinense',
    26420.0: 'Instituto Federal Farroupilha',
    26434.0: 'Instituto Federal Fluminense',
    26407.0: 'Instituto Federal Goiano',
    26436.0: 'Instituto Federal Sul-rio-grandense',
    26427.0: 'Instituto Federal da Bahia',
    26417.0: 'Instituto Federal da Paraíba',
    26402.0: 'Instituto Federal de Alagoas',
    26428.0: 'Instituto Federal de Brasília',
    26429.0: 'Instituto Federal de Educação, Ciência e Tecnologia de Goiás',
    26409.0: 'Instituto Federal de Minas Gerais',
    26418.0: 'Instituto Federal de Pernambuco',
    26421.0: 'Instituto Federal de Rondônia',
    26437.0: 'Instituto Federal de Roraima',
    26438.0: 'Instituto Federal de Santa Catarina',
    26423.0: 'Instituto Federal de Sergipe',
    26439.0: 'Instituto Federal de São Paulo',
    26425.0: 'Instituto Federal do Acre',
    26426.0: 'Instituto Federal do Amapá',
    26403.0: 'Instituto Federal do Amazonas',
    26405.0: 'Instituto Federal do Ceará',
    26406.0: 'Instituto Federal do Espírito Santo',
    26408.0: 'Instituto Federal do Maranhão',
    26414.0: 'Instituto Federal do Mato Grosso',
    26415.0: 'Instituto Federal do Mato Grosso do Sul',
    26410.0: 'Instituto Federal do Norte de Minas Gerais',
    26432.0: 'Instituto Federal do Paraná',
    26416.0: 'Instituto Federal do Pará',
    26431.0: 'Instituto Federal do Piauí',
    26435.0: 'Instituto Federal do Rio Grande do Norte',
    26419.0: 'Instituto Federal do Rio Grande do Sul',
    26433.0: 'Instituto Federal do Rio de Janeiro',
    26430.0: 'Instituto Federal do Sertão de Pernambuco',
    26411.0: 'Instituto Federal do Sudeste de Minas Gerais',
    26412.0: 'Instituto Federal do Sul de Minas Gerais',
    26424.0: 'Instituto Federal do Tocantins',
    26413.0: 'Instituto Federal do Triângulo Mineiro',
    30204.0: 'Instituto Nacional da Propriedade Industrial',
    22201.0: 'Instituto Nacional de Colonização e Reforma Agrária',
    26290.0: 'Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira',
    30203.0: 'Instituto Nacional de Metrologia, Qualidade e Tecnologia',
    24208.0: 'Instituto Nacional de Tecnologia da Informação',
    37202.0: 'Instituto Nacional do Seguro Social',
    61201.0: 'Instituto de Pesquisa Econômica Aplicada',
    44206.0: 'Instituto de Pesquisas Jardim Botânico do Rio de Janeiro',
    20411.0: 'Instituto do Patrimônio Histórico e Artístico Nacional',
    22000.0: 'Ministério da Agricultura, Pecuária e Abastecimento - Unidades com vínculo direto',
    55000.0: 'Ministério da Cidadania - Unidades com vínculo direto',
    24000.0: 'Ministério da Ciência, Tecnologia, Inovações e Comunicações - Unidades com vínculo direto',
    52000.0: 'Ministério da Defesa - Unidades com vínculo direto',
    25000.0: 'Ministério da Economia - Unidades com vínculo direto',
    26000.0: 'Ministério da Educação - Unidades com vínculo direto',
    39000.0: 'Ministério da Infraestrutura - Unidades com vínculo direto',
    30000.0: 'Ministério da Justiça e Segurança Pública - Unidades com vínculo direto',
    81000.0: 'Ministério da Mulher, Família e Direitos Humanos - Unidades com vínculo direto',
    58000.0: 'Ministério da Pesca e Aquicultura - Unidades com vínculo direto',
    33000.0: 'Ministério da Previdência Social - Unidades com vínculo direto',
    36000.0: 'Ministério da Saúde - Unidades com vínculo direto',
    41000.0: 'Ministério das Comunicações - Unidades com vínculo direto',
    35000.0: 'Ministério das Relações Exteriores - Unidades com vínculo direto',
    32000.0: 'Ministério de Minas e Energia - Unidades com vínculo direto',
    49000.0: 'Ministério do Desenvolvimento Agrário - Unidades com vínculo direto',
    53000.0: 'Ministério do Desenvolvimento Regional - Unidades com vínculo direto',
    44000.0: 'Ministério do Meio Ambiente - Unidades com vínculo direto',
    38000.0: 'Ministério do Trabalho e Emprego - Unidades com vínculo direto',
    54000.0: 'Ministério do Turismo - Unidades com vínculo direto',
    20302.0: 'Nuclebrás Equipamentos Pesados S.A.',
    20101.0: 'Presidência da República',
    90000.0: 'Reserva de Contingência',
    20129.0: 'Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agrário',
    20122.0: 'Secretaria Nacional de Políticas para Mulheres',
    30905.0: 'Secretaria Nacional do Consumidor Fundo',
    69000.0: 'Secretaria da Micro e Pequena Empresa',
    61000.0: 'Secretaria de Assuntos Estratégicos',
    62000.0: 'Secretaria de Aviação Civil',
    64000.0: 'Secretaria de Direitos Humanos',
    67000.0: 'Secretaria de Políticas de Promoção da Igualdade Racial',
    68000.0: 'Secretaria de Portos',
    25207.0: 'Serviço Federal de Processamento de Dados',
    44208.0: 'Serviço Florestal Brasileiro',
    33206.0: 'Superintendência Nacional de Previdência Complementar',
    20603.0: 'Superintendência da Zona Franca de Manaus',
    53207.0: 'Superintendência de Desenvolvimento do Centro-Oeste',
    25208.0: 'Superintendência de Seguros Privados',
    53202.0: 'Superintendência do Desenvolvimento da Amazônia',
    53203.0: 'Superintendência do Desenvolvimento do Nordeste',
    24216.0: 'TELECOMUNICACOES BRASILEIRAS S/A',
    26452.0: 'UNIVERSIDADE FEDERAL DE CATALAO',
    26453.0: 'UNIVERSIDADE FEDERAL DE JATAI',
    26454.0: 'UNIVERSIDADE FEDERAL DE RONDONOPOLIS',
    26456.0: 'UNIVERSIDADE FEDERAL DO AGRESTE DE PERNAMBUCO',
    26455.0: 'UNIVERSIDADE FEDERAL DO DELTA DO PARNAIBA',
    26457.0: 'UNIVERSIDADE FEDERAL DO NORTE DE TOCANTINS',
    26236.0: 'Universidade Federal Fluminense',
    26253.0: 'Universidade Federal Rural da Amazônia',
    26248.0: 'Universidade Federal Rural de Pernambuco',
    26249.0: 'Universidade Federal Rural do Rio de Janeiro',
    26264.0: 'Universidade Federal Rural do Semi-Árido',
    26232.0: 'Universidade Federal da Bahia',
    26440.0: 'Universidade Federal da Fronteira Sul',
    26267.0: 'Universidade Federal da Integração Latino-Americana',
    26240.0: 'Universidade Federal da Paraíba',
    26231.0: 'Universidade Federal de Alagoas',
    26260.0: 'Universidade Federal de Alfenas',
    26252.0: 'Universidade Federal de Campina Grande',
    26235.0: 'Universidade Federal de Goiás',
    26261.0: 'Universidade Federal de Itajubá',
    26237.0: 'Universidade Federal de Juiz de Fora',
    26263.0: 'Universidade Federal de Lavras',
    26238.0: 'Universidade Federal de Minas Gerais',
    26277.0: 'Universidade Federal de Ouro Preto',
    26242.0: 'Universidade Federal de Pernambuco',
    26250.0: 'Universidade Federal de Roraima',
    26246.0: 'Universidade Federal de Santa Catarina',
    26247.0: 'Universidade Federal de Santa Maria',
    26262.0: 'Universidade Federal de São Paulo',
    26282.0: 'Universidade Federal de Viçosa',
    26449.0: 'Universidade Federal do Cariri',
    26233.0: 'Universidade Federal do Ceará',
    26234.0: 'Universidade Federal do Espírito Santo',
    26269.0: 'Universidade Federal do Estado do Rio de Janeiro',
    26447.0: 'Universidade Federal do Oeste da Bahia',
    26441.0: 'Universidade Federal do Oeste do Pará',
    26241.0: 'Universidade Federal do Paraná',
    26239.0: 'Universidade Federal do Pará',
    26351.0: 'Universidade Federal do Recôncavo da Bahia',
    26273.0: 'Universidade Federal do Rio Grande',
    26243.0: 'Universidade Federal do Rio Grande do Norte',
    26244.0: 'Universidade Federal do Rio Grande do Sul',
    26245.0: 'Universidade Federal do Rio de Janeiro',
    26450.0: 'Universidade Federal do Sul da Bahia',
    26448.0: 'Universidade Federal do Sul e Sudeste do Pará',
    26254.0: 'Universidade Federal do Triângulo Mineiro',
    26255.0: 'Universidade Federal dos Vales do Jequitinhonha e Mucuri',
    26258.0: 'Universidade Tecnológica Federal do Paraná',
    26442.0: 'Universidade da Integração Internacional da Lusofonia Afro-Brasileira',
    29209.0: 'VALEC Engenharia, Construções e Ferrovias S.A.'}


dicc_unidad_gestora = {323030.0: 'AG. NAC.DO PETROLEO GAS NAT.E BIOCOM',
    533001.0: 'AGENCIA DE DESENVOLVIMENTO DA AMAZONIA',
    203001.0: 'AGENCIA ESPACIAL BRASILEIRA/AEB',
    113214.0: 'AGENCIA NACIONAL DE AVIACAO CIVIL',
    122002.0: 'AGENCIA NACIONAL DE AVIACAO CIVIL - F. AEROV.',
    323028.0: 'AGENCIA NACIONAL DE ENERGIA ELETRICA',
    253003.0: 'AGENCIA NACIONAL DE SAUDE SUPLEMENTAR',
    413001.0: 'AGENCIA NACIONAL DE TELECOMUNICACOES-SEDE',
    682010.0: 'AGENCIA NACIONAL DE TRANSPORTES AQUAVIARIOS',
    393002.0: 'AGENCIA NACIONAL DE TRANSPORTES AQUAVIARIOS',
    393001.0: 'AGENCIA NACIONAL DE TRANSPORTES TERRESTRES',
    253002.0: 'AGENCIA NACIONAL DE VIGILANCIA SANITARIA',
    203003.0: 'AGENCIA NACIONAL DO CINEMA',
    913001.0: 'AUTORIDADE PUBLICA OLIMPICA',
    173057.0: 'BANCO CENTRAL DO BRASIL',
    123001.0: 'CAIXA FINANCIAMENTO IMOBILIARIO AERONAUTICA',
    154999.0: 'CAPES - DIFERENCA CAMBIAL',
    179083.0: 'CASA DA MOEDA DO BRASIL',
    153010.0: 'CENTRO FED.DE EDUC.TECNOL.CELSO S.DA FONSECA',
    153015.0: 'CENTRO FEDERAL DE EDUCACAO TECNOLOGICA DE MG',
    245209.0: 'CENTRO NACIONAL DE TECNOLOGIA ELETRONICA AVAN',
    540001.0: 'CGOFC - SETORIAL/MTUR',
    275068.0: 'CIA BRASILEIRA DE TRENS URBANOS-ADM.CENTRAL',
    195006.0: 'CIA DE DES.DOS VALES DO S.FRANC.E DO PARNAIBA',
    225001.0: 'CIA.DE ENTREPOSTOS E ARMAZENS GER.DE S.PAULO',
    113209.0: 'CNEN-ORCAMENTO E FINANCAS',
    364001.0: 'CNPQ - ADMINISTRACAO CENTRAL',
    364999.0: 'CNPQ - DIFERENCIA CAMBIAL',
    153167.0: 'COLEGIO PEDRO II',
    173030.0: 'COMISSAO DE VALORES MOBILIARIOS',
    195008.0: 'COMPANHIA DE DESENVOLVIMENTO DE BARCARENA',
    495001.0: 'COMPANHIA DE PESQUISA DE RECURSOS MINERAIS',
    396005.0: 'COMPANHIA DOCA DO RIO GRANDE DO NORTE',
    396003.0: 'COMPANHIA DOCAS DO CEARA',
    399002.0: 'COMPANHIA DOCAS DO ESPIRITO SANTO',
    396002.0: 'COMPANHIA DOCAS DO ESTADO DA BAHIA',
    396006.0: 'COMPANHIA DOCAS DO ESTADO DE SAO PAULO',
    396004.0: 'COMPANHIA DOCAS DO PARA',
    396001.0: 'COMPANHIA DOCAS DO RIO DE JANEIRO',
    135100.0: 'COMPANHIA NACIONAL DE ABASTECIMENTO',
    303001.0: 'CONSELHO ADMINISTRATIVO DE DEFESA ECONOMICA',
    364102.0: 'CONSELHO NAC DE DESENV CIENT E TECNOLOGICO',
    400042.0: 'COORD-GERAL DE ORC., FIN. E CONT.-CGOFC (MTP)',
    380010.0: 'COORD-GERAL DE ORCAM., FIN. E CONTABILIDADE',
    380910.0: 'COORD-GERAL DE ORCAMENTO, FIN. E CONT.- CGOFC',
    443019.0: 'COORD. DE PLAN. ORCAMENTO E FIN./COPLAN/JBRJ',
    110060.0: 'COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU',
    130101.0: 'COORD.-GERAL DE ORCAMENTO E FINANCAS-MAPA',
    333001.0: 'COORD.GERAL DE ORC. FIN. E CONTABILIDADE',
    320002.0: 'COORD.GERAL DE ORCAM.E FIN./M.M.E',
    510001.0: 'COORD.GERAL DE ORCAMENTO, FINANCAS E CONTAB.',
    420002.0: 'COORD.GERAL DE PLAN. ORC. FIN. E CONTAB./MINC',
    340002.0: 'COORD.GERAL DE PLAN. ORC. FIN. E CONTAB/FNC',
    200337.0: 'COORDENACAO DE ORCAMENTO E FINANCAS - COF/DPF',
    200278.0: 'COORDENACAO DE ORCAMENTO E FINANCAS - PRF',
    513001.0: 'COORDENACAO DE ORCAMENTO E FINANCAS DO FRGPS',
    443003.0: 'COORDENACAO DE ORCAMENTO E FINANCAS.',
    200336.0: 'COORDENACAO DE ORCAMENTO FINANCAS CONTABILIDA',
    201002.0: 'COORDENACAO-GERAL DE ORC. E FINANCAS/MP',
    330002.0: 'COORDENACAO-GERAL DE ORC. FIN.E CONTABILIDADE',
    280102.0: 'COORDENACAO-GERAL DE ORCAM.FINAN.CONTAB/MDIC',
    240102.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS',
    410002.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS',
    200094.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS-MJ',
    240005.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS-MRE',
    240101.0: 'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',
    410003.0: 'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',
    130150.0: 'COORDENACAO-GERAL DO FUNDO DE TERRAS',
    490003.0: 'CREDITO FUNDIARIO',
    160075.0: 'D CONT - SETORIAL FINANCEIRA',
    393003.0: 'DEPART.NAC.INFRA ESTRUTURA TRANSPORTES.',
    180002.0: 'DEPARTAMENTO DE GESTAO INTERNA',
    110407.0: 'DEPARTAMENTO DE PLANEJ, ORC E FINANCAS (MD)',
    113802.0: 'DEPARTAMENTO NAC. DE OBRAS CONTRA AS SECAS/UO',
    323002.0: 'DEPARTAMENTO NAC. DE PRODUCAO MINERAL - SEDE',
    273087.0: 'DEPARTAMENTO NAC. ESTRADAS E RODAGEM-EXTINCAO',
    200333.0: 'DEPEN - DIRETORIA EXECUTIVA',
    200109.0: 'DEPTO.DE POLICIA RODOVIARIA FEDERAL',
    120002.0: 'DIRETORIA DE ECON E FINANCAS DA AERONAUTICA',
    773009.0: 'DIRETORIA DE FINANCAS DA MARINHA - AMAZUL',
    773008.0: 'DIRETORIA DE FINANCAS DA MARINHA - CCCPM',
    773001.0: 'DIRETORIA DE FINANCAS DA MARINHA-SISTEMA-PAIS',
    673001.0: 'DIRETORIA DE FINANCAS-SISTEMA PARA O PAIS/MM',
    873001.0: 'DIRETORIA DE FINANCAS-SISTEMA PARA O PAIS/MM',
    370001.0: 'DIRETORIA DE GESTAO INTERNA(CGU)',
    110174.0: 'DIRETORIA DE GESTAO INTERNA/SE/CGU',
    373001.0: 'DPTO. DE ADMINISTRACAO FINANCEIRA-DAF - INCRA',
    135037.0: 'EMBRAPA-SETORIAL',
    115406.0: 'EMPRESA BRASIL DE COMUNICACAO S.A',
    415001.0: 'EMPRESA BRASILEIRA DE CORREIOS E TELEGRAFOS',
    155007.0: 'EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES',
    325001.0: 'EMPRESA DE PESQUISA ENERGETICA',
    395001.0: 'EMPRESA DE PLANEJAMENTO E LOGISTICA S.A - EPL',
    275060.0: 'EMPRESA DE TRENS URBANOS DE PORTO ALEGRE S/A',
    167999.0: 'FDO EXERCITO - DIFERENCA CAMBIAL',
    365001.0: 'FINANCIADORA DE ESTUDOS E PROJETOS',
    154421.0: 'FUND. UNIVERSIDADE FEDERAL VALE SAO FRANCISCO',
    154003.0: 'FUND.COORD.DE APERF.DE PESSOAL NIVEL SUPERIOR',
    154032.0: 'FUND.UNIV.FED.DE.CIENC.DA SAUDE DE P.ALEGRE',
    244001.0: 'FUNDACAO ALEXANDRE DE GUSMAO',
    344042.0: 'FUNDACAO BIBLIOTECA NACIONAL',
    344001.0: 'FUNDACAO CASA DE RUI BARBOSA',
    344041.0: 'FUNDACAO CULTURAL PALMARES',
    114702.0: 'FUNDACAO ESCOLA NACIONAL DE ADM. PUBLICA',
    114601.0: 'FUNDACAO IBGE-ADMINISTRACAO CENTRAL/RJ',
    344002.0: 'FUNDACAO JOAQUIM NABUCO',
    403201.0: 'FUNDACAO NACIONAL DE ARTES',
    255003.0: 'FUNDACAO NACIONAL DE SAUDE - AP',
    255000.0: 'FUNDACAO NACIONAL DE SAUDE - DF',
    255008.0: 'FUNDACAO NACIONAL DE SAUDE - ES',
    255011.0: 'FUNDACAO NACIONAL DE SAUDE - MT',
    255014.0: 'FUNDACAO NACIONAL DE SAUDE - PA',
    255015.0: 'FUNDACAO NACIONAL DE SAUDE - PB',
    194088.0: 'FUNDACAO NACIONAL DO INDIO - U.O.',
    164204.0: 'FUNDACAO OSORIO',
    254420.0: 'FUNDACAO OSWALDO CRUZ',
    154054.0: 'FUNDACAO UNIVERS.FED. DE MATO GROSSO DO SUL',
    154040.0: 'FUNDACAO UNIVERSIDADE DE BRASILIA - FUB',
    154039.0: 'FUNDACAO UNIVERSIDADE DO AMAZONAS',
    154041.0: 'FUNDACAO UNIVERSIDADE DO MARANHAO',
    154502.0: 'FUNDACAO UNIVERSIDADE FED. DA GRANDE DOURADOS',
    154045.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE MATO GROSSO',
    154047.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE PELOTAS',
    154055.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA',
    154069.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE S.J.DEL-REI',
    154049.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE SAO CARLOS',
    154050.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE SERGIPE',
    154043.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE UBERLANDIA',
    154503.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO ABC',
    154044.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO ACRE',
    154215.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO AMAPA',
    154359.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO PAMPA',
    154048.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO PIAUI',
    154419.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO TOCANTINS',
    264001.0: 'FUNDACENTRO - FUND.JORGE DUPRAT/CTN/SEDE - SP',
    537001.0: 'FUNDO CONSTITUCIONAL DE FINANCIAM.DO NORDESTE',
    170392.0: 'FUNDO CONSTITUCIONAL DO DISTRITO FEDERAL',
    537002.0: 'FUNDO CONSTITUCIONAL FINANCIAMENTO NORTE',
    537003.0: 'FUNDO CONSTITUCIONL DO CENTRO OESTE',
    173065.0: 'FUNDO CONTINGENTE DA EXTINTA RFFSA-FC',
    277001.0: 'FUNDO DA MARINHA MERCANTE',
    170380.0: 'FUNDO DE APOIO AO DESENVOLVIMENTO SOCIAL',
    170381.0: 'FUNDO DE COMPENSACAO E VARIACAO SALARIAL',
    130137.0: 'FUNDO DE DEFESA DA ECON.CAFEEIRA/FUNCAFE/SPA',
    200401.0: 'FUNDO DE DEFESA DOS DIREITOS DIFUSOS',
    533008.0: 'FUNDO DE DESENVOLVIMENTO DA AMAZONIA',
    537004.0: 'FUNDO DE DESENVOLVIMENTO DO CENTRO-OESTE',
    533009.0: 'FUNDO DE DESENVOLVIMENTO DO NORDESTE',
    179103.0: 'FUNDO DE ESTABILIDADE DO SEGURO RURAL',
    287001.0: 'FUNDO DE GAR.P/PROMOC.DA COMPETITIVIDADE±FGPC',
    170356.0: 'FUNDO DE GARANTIA A EXPORTACAO-BNDES',
    110245.0: 'FUNDO DE IMPRENSA NACIONAL/EXEC.ORC.FINANC.',
    413047.0: 'FUNDO DE UNIVERS.DOS SERV.TELECOMUNICACOES',
    167086.0: 'FUNDO DO EXERCITO',
    187002.0: 'FUNDO GERAL DE TURISMO-FUNGETUR',
    240901.0: 'FUNDO NAC.DE DESENV. CIENT. E TECNOLOGICO',
    570901.0: 'FUNDO NAC.P/A CRIANCA E O ADOLESC.SET.ORC/FIN',
    200246.0: 'FUNDO NACIONAL ANTIDROGAS',
    110246.0: 'FUNDO NACIONAL ANTIDROGAS',
    540030.0: 'FUNDO NACIONAL DA CULTURA - FNC',
    330013.0: 'FUNDO NACIONAL DE ASSISTENCIA SOCIAL',
    110591.0: 'FUNDO NACIONAL DE AVIACAO CIVIL',
    201924.0: 'FUNDO NACIONAL DE DESENVOLVIMENTO',
    153173.0: 'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
    560015.0: 'FUNDO NACIONAL DE HABIT. DE INTERESSE SOCIAL',
    200320.0: 'FUNDO NACIONAL DE SEG. E EDUCACAO DE TRANSITO',
    200331.0: 'FUNDO NACIONAL DE SEGURANCA PUBLICA - FNSP',
    307002.0: 'FUNDO NACIONAL DO IDOSO',
    207001.0: 'FUNDO NACIONAL DO IDOSO',
    570903.0: 'FUNDO NACIONAL DO IDOSO - SET.ORC/FIN',
    307001.0: 'FUNDO NACIONAL PARA A CRIANCA E O ADOLESCENTE',
    110244.0: 'FUNDO NACIONAL PARA A CRIANCA E O ADOLESCENTE',
    699999.0: 'FUNDO NAVAL - DIFERENCA CAMBIAL',
    410007.0: 'FUNDO P/O DESENV.TECNOL.DAS TELECOMUNICACOES',
    170474.0: 'FUNDO SOBERANO DO BRASIL',
    110101.0: 'GABINETE DA VICE-PRESIDENCIA DA REPUBLICA',
    366001.0: 'HOSPITAL CRISTO REDENTOR S/A',
    155001.0: 'HOSPITAL DE CLINICAS DE PORTO ALEGRE',
    366002.0: 'HOSPITAL FEMINA S/A',
    366003.0: 'HOSPITAL NOSSA SENHORA DA CONCEICAO S/A',
    193034.0: 'IBAMA - INST.BRASILEIRO MEIO AMBIENTE/MATRIZ',
    193116.0: 'IBAMA - SUPERINTENDENCIA DE PERNAMBUCO/PE',
    193122.0: 'IBAMA - SUPERINTENDENCIA DE RORAIMA/RR',
    193125.0: 'IBAMA - SUPERINTENDENCIA DE SANTA CATARINA/SC',
    193129.0: 'IBAMA - SUPERINTENDENCIA DE SAO PAULO/SP',
    193105.0: 'IBAMA - SUPERINTENDENCIA DO ACRE/AC',
    193107.0: 'IBAMA - SUPERINTENDENCIA DO ESPIRITO SANTO/ES',
    193113.0: 'IBAMA - SUPERINTENDENCIA DO MATO GROSSO/MT',
    193114.0: 'IBAMA - SUPERINTENDENCIA DO PARA/PA',
    193183.0: 'IBAMA - SUPERINTENDENCIA DO TOCANTINS/TO',
    193112.0: 'IBAMA - SUPERINTENDENCIA MATO GROSSO SUL/MS',
    193120.0: 'IBAMA - SUPERINTENDENCIA RIO GRANDE NORTE/RN',
    158124.0: 'IF GOIANO',
    158143.0: 'IFB - REITORIA - BRASILIA-DF',
    158138.0: 'IFPB - REITORIA',
    168002.0: 'INDUSTRIA DE MATERIAL BELICO DO BRASIL/GESTOR',
    113206.0: 'INDUSTRIAS NUCLEARES DO BRASIL S/A - INB',
    158129.0: 'INST FED DE EDUC CIENC E TECNOLOGIA BAIANO',
    158148.0: 'INST. FED. DE EDUC.,CIENC. E TEC. DE RONDONIA',
    158009.0: 'INST. FED. DO PARANA/ REITORIA',
    443032.0: 'INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE',
    158274.0: 'INST.FED. FLUMINENSE/CAMPUS CAMPOS-CENTRO',
    158149.0: 'INST.FED.DE ED.,CIENC.E TEC.DO S.PERNAMBUCANO',
    158126.0: 'INST.FED.DE EDUC.,CIE.E TEC.SUL-RIO-GRANDENSE',
    158145.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DA BAHIA',
    158147.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE ALAGOAS',
    158153.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE GOIAS',
    158122.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE MINAS GERAIS',
    158136.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE PERNAMBUCO',
    158152.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE RORAIMA',
    158134.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE SERGIPE',
    158516.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE STA.CAT/IFSC',
    158156.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO ACRE',
    158150.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO AMAPA',
    158142.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO AMAZONAS',
    158133.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO CEARA',
    158151.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO ESP.SANTO',
    158128.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO MARANHAO',
    158132.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO MAT.G.DO SUL',
    158144.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO MATO GROSSO',
    158121.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO NORTE DE MG',
    158135.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO PARA',
    158146.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI',
    158155.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO RN',
    158141.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO RS',
    158137.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO SUL DE MG',
    158131.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO TOCANTINS',
    158099.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO TRIA.MINEIRO',
    158127.0: 'INST.FED.DE EDUC.,CIENC.E TEC.FARROUPILHA',
    158139.0: 'INST.FED.DE EDUC.,CIENC.E TEC.FLUMINENSE',
    153978.0: 'INST.NACIONAL DE EST.E PESQUISAS EDUCACIONAIS',
    423001.0: 'INSTITUTO BRASILEIRO DE MUSEUS - IBRAM',
    185001.0: 'INSTITUTO BRASILEIRO DE TURISMO - EM EXTINCAO',
    113601.0: 'INSTITUTO DE PESQUISA ECONOMICA APLICADA',
    403101.0: 'INSTITUTO DO PATRIMONIO HIST. E ART. NACIONAL',
    158123.0: 'INSTITUTO FED CIENCIA TECNOL SUDESTE MG',
    158125.0: 'INSTITUTO FEDERAL CATARINENSE - REITORIA',
    158154.0: 'INSTITUTO FEDERAL DE SAO PAULO',
    183023.0: 'INSTITUTO NAC.DE METROLOG. QUALID. E TECNOLOG',
    243001.0: 'INSTITUTO NAC.DE TECNOLOGIA DA INFORMACAO ITI',
    183038.0: 'INSTITUTO NACIONAL DA PROPRIEDADE INDUSTRIAL',
    120999.0: 'MAER - DIFERENCA CAMBIAL',
    211999.0: 'MARINHA - DIFERENCA CAMBIAL',
    240999.0: 'MRE - DIFERENCA CAMBIAL',
    113208.0: 'NUCLEBRAS EQUIPAMENTOS PESADOS S/A-NUCLEP',
    530002.0: 'ORCAMENTO E FINANCAS/MDR',
    170358.0: 'PROCURADORIA DA FAZ.NAC. NO ESTADO DO AMAPA',
    170196.0: 'PROCURADORIA DA FAZENDA NACI0NAL/GO',
    170076.0: 'PROCURADORIA DA FAZENDA NACIONAL - BA',
    170026.0: 'PROCURADORIA DA FAZENDA NACIONAL - MA',
    170086.0: 'PROCURADORIA DA FAZENDA NACIONAL - MG',
    170033.0: 'PROCURADORIA DA FAZENDA NACIONAL - PI',
    170357.0: 'PROCURADORIA DA FAZENDA NACIONAL EM RONDONIA',
    170101.0: 'PROCURADORIA DA FAZENDA NACIONAL-ES',
    170107.0: 'PROCURADORIA DA FAZENDA NACIONAL-MS',
    170154.0: 'PROCURADORIA DA FAZENDA NACIONAL-PR',
    170073.0: 'PROCURADORIA DA FAZENDA NACIONAL-SE',
    170237.0: 'PROCURADORIA DA FAZENDA NACIONAL/AC',
    170232.0: 'PROCURADORIA DA FAZENDA NACIONAL/AL',
    170233.0: 'PROCURADORIA DA FAZENDA NACIONAL/AM',
    170230.0: 'PROCURADORIA DA FAZENDA NACIONAL/CE',
    170229.0: 'PROCURADORIA DA FAZENDA NACIONAL/MT',
    170215.0: 'PROCURADORIA DA FAZENDA NACIONAL/PA',
    170231.0: 'PROCURADORIA DA FAZENDA NACIONAL/PB',
    170234.0: 'PROCURADORIA DA FAZENDA NACIONAL/RN',
    170238.0: 'PROCURADORIA DA FAZENDA NACIONAL/RR',
    170167.0: 'PROCURADORIA DA FAZENDA NACIONAL/SC',
    170285.0: 'PROCURADORIA FAZ.NACIONAL NO EST.TOCANTINS',
    170008.0: 'PROCURADORIA GERAL DA FAZENDA NACIONAL',
    170265.0: 'PROCURADORIA REGIONAL DA F.NACIONAL/4A REGIAO',
    170204.0: 'PROCURADORIA-REGIONAL DA FAZ.NAC.1A.REGIAO/DF',
    170266.0: 'PROCURADORIA-REGIONAL DA FAZENDA NACIONAL/PE',
    170267.0: 'PROCURADORIA-REGIONAL DA FAZENDA NACIONAL/RJ',
    170268.0: 'PROCURADORIA-REGIONAL DA FAZENDA NACIONAL/SP',
    158157.0: 'REITORIA',
    194040.0: 'RENDA DO PATRIMONIO INDIGENA',
    390001.0: 'RESERVA DE CONTINGENCIA/MEFP',
    110690.0: 'SEC.ESPEC.DE AGRIC.FAMIL.E DO DESENV.AGRARIO',
    690001.0: 'SECRETARIA DA MICRO E PEQUENA EMPRESA',
    170010.0: 'SECRETARIA DA RECEITA FEDERAL DO BRASIL-RFB',
    110005.0: 'SECRETARIA DE ADMINISTRACAO-SET.ORC.E FIN./PR',
    110355.0: 'SECRETARIA DE ASSUNTOS ESTRATEGICOS-SAE/PR',
    110590.0: 'SECRETARIA DE AVIACAO CIVIL/PR',
    200016.0: 'SECRETARIA DE DIREITOS HUMANOS/PR',
    121002.0: 'SECRETARIA DE ECON. E FIN.DA AER.- F.AER.',
    238012.0: 'SECRETARIA DE POLIT. DE PROM.DA IGUALD.RACIAL',
    200021.0: 'SECRETARIA DE POLITICAS PARA AS MULHERES',
    110680.0: 'SECRETARIA DE PORTOS/PR',
    110745.0: 'SECRETARIA ESPECIAL DE AQUICULTURA E PESCA/PR',
    560003.0: 'SECRETARIA EXECUTIVA - MINISTERIO DAS CIDADES',
    110008.0: 'SECRETARIA EXECUTIVA-MPA',
    806001.0: 'SERPRO-SEDE - DEPARTAMENTO FINANCEIRO',
    550002.0: 'SETORIAL DE ORCAMENTO E FINANCAS/MC',
    180077.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA - (ME)',
    323100.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA - ANM',
    810002.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA - MDH',
    170013.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA / ME',
    443045.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA DO FNMA',
    447001.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA DO FNMC',
    440088.0: 'SETORIAL PROG.ORCAMENTARIA E FINANCEIRA-SFB',
    130214.0: 'SETORIAL PROG.ORCAMENTARIA E FINANCEIRA-SFB',
    250088.0: 'SPO-COORD.-GERAL DE ORC.E FINANCAS/MS',
    179999.0: 'STN - EXTERIOR - DIF.CAMBIAL',
    490002.0: 'SUBSEC. DE PLANEJ., ORCAMENTO E ADMINISTRACAO',
    440002.0: 'SUBSECRET.PLANEJAM.ORCAM.E ADMINIST±SPOA(MMA)',
    390002.0: 'SUBSECRETARIA DE PLAN.,ORCAM.E ADMIN.SETORIAL',
    150014.0: 'SUBSECRETARIA DE PLANEJ. E ORCAMENTO SPO(MEC)',
    533018.0: 'SUPERINT. DO DESENVOLVIMENTO DO CENTRO-OESTE',
    113243.0: 'SUPERINT. INFRAESTRUTURA AEROPORTUARIA - ANAC',
    533013.0: 'SUPERINTEND. DO DESENVOLVIMENTO DA AMAZONIA',
    193028.0: 'SUPERINTENDENCIA DA ZONA FRANCA DE MANAUS/AM',
    173039.0: 'SUPERINTENDENCIA DE SEGUROS PRIVADOS - RJ',
    533014.0: 'SUPERINTENDENCIA DO DESENVOLV. DO NORDESTE',
    242160.0: 'TELECOMUNICACOES BRASILEIRAS S/A',
    153031.0: 'UNIFESP-UNIVERSIDADE FEDERAL DE SAO PAULO',
    154034.0: 'UNIRIO UNIVERSIDADE FEDERAL DO ESTADO RJ',
    158658.0: 'UNIV. FEDERAL DA INTEGRACAO LATINO-AMERICANA',
    158565.0: 'UNIV.DA INTEG.INTERN.DA LUSOF.AFRO-BRASILEIRA',
    153036.0: 'UNIVERSIDADE FED.VALES JEQUITINHONHA E MUCURI',
    153038.0: 'UNIVERSIDADE FEDERAL DA BAHIA',
    158517.0: 'UNIVERSIDADE FEDERAL DA FRONTEIRA SUL',
    153065.0: 'UNIVERSIDADE FEDERAL DA PARAIBA',
    153037.0: 'UNIVERSIDADE FEDERAL DE ALAGOAS',
    153028.0: 'UNIVERSIDADE FEDERAL DE ALFENAS',
    158195.0: 'UNIVERSIDADE FEDERAL DE CAMPINA GRANDE',
    156679.0: 'UNIVERSIDADE FEDERAL DE CATALAO',
    153052.0: 'UNIVERSIDADE FEDERAL DE GOIAS',
    153030.0: 'UNIVERSIDADE FEDERAL DE ITAJUBA',
    156678.0: 'UNIVERSIDADE FEDERAL DE JATAI',
    153061.0: 'UNIVERSIDADE FEDERAL DE JUIZ DE FORA',
    153032.0: 'UNIVERSIDADE FEDERAL DE LAVRAS',
    153062.0: 'UNIVERSIDADE FEDERAL DE MINAS GERAIS',
    154046.0: 'UNIVERSIDADE FEDERAL DE OURO PRETO',
    153080.0: 'UNIVERSIDADE FEDERAL DE PERNAMBUCO',
    156677.0: 'UNIVERSIDADE FEDERAL DE RONDONOPOLIS',
    154080.0: 'UNIVERSIDADE FEDERAL DE RORAIMA',
    153163.0: 'UNIVERSIDADE FEDERAL DE SANTA CATARINA',
    153164.0: 'UNIVERSIDADE FEDERAL DE SANTA MARIA',
    154051.0: 'UNIVERSIDADE FEDERAL DE VICOSA',
    156687.0: 'UNIVERSIDADE FEDERAL DO AGRESTE DE PERNAMBUCO',
    158719.0: 'UNIVERSIDADE FEDERAL DO CARIRI',
    153045.0: 'UNIVERSIDADE FEDERAL DO CEARA',
    156680.0: 'UNIVERSIDADE FEDERAL DO DELTA DO PARNAIBA',
    153046.0: 'UNIVERSIDADE FEDERAL DO ESPIRITO SANTO',
    156763.0: 'UNIVERSIDADE FEDERAL DO NORTE DE TOCANTINS',
    158717.0: 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA',
    158515.0: 'UNIVERSIDADE FEDERAL DO OESTE DO PARA',
    153063.0: 'UNIVERSIDADE FEDERAL DO PARA',
    153079.0: 'UNIVERSIDADE FEDERAL DO PARANA',
    158092.0: 'UNIVERSIDADE FEDERAL DO RECONCAVO DA BAHIA',
    153115.0: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
    154042.0: 'UNIVERSIDADE FEDERAL DO RIO GRANDE - FURG',
    153103.0: 'UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE',
    153114.0: 'UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL',
    158720.0: 'UNIVERSIDADE FEDERAL DO SUL DA BAHIA',
    158718.0: 'UNIVERSIDADE FEDERAL DO SUL E SUDESTE DO PARA',
    153035.0: 'UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO',
    153056.0: 'UNIVERSIDADE FEDERAL FLUMINENSE',
    153034.0: 'UNIVERSIDADE FEDERAL RURAL DA AMAZONIA',
    153165.0: 'UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO',
    153166.0: 'UNIVERSIDADE FEDERAL RURAL DO RIO DE JANEIRO',
    153033.0: 'UNIVERSIDADE FEDERAL RURAL DO SEMI-ARIDO - RN',
    153019.0: 'UNIVERSIDADE TECNOLOGICA FEDERAL DO PARANA',
    275075.0: 'VALEC ENGENHARIA CONSTRUCOES E FERROVIAS S/A.'}


dicc_cat_economica = {
    'Receitas Correntes': 'Ingresos Corrientes',
    'Receitas de Capital': 'Ingresos de Capital',
    'Receitas Correntes - intra-orçamentárias': 'Ingresos Corrientes - intra-presupuestarios',
    'Sem informação': 'Desconocido',
    'Receitas de Capital - intra-orçamentárias': 'Ingresos de Capital - intra-presupuestarios'
    }


dicc_origen_ingreso = {
    'Outras Receitas Correntes': 'Otros Ingresos Corrientes',
    'Receita de Serviços': 'Ingresos por Servicios',
    'Transferências de Capital': 'Transferencias de Capital',
    'Alienação de Bens': 'Venta de Activos',
    'Receita Agropecuária': 'Ingresos Agropecuarios',
    'Transferências Correntes': 'Transferencias Corrientes',
    'Receita Patrimonial': 'Ingresos Patrimoniales',
    'Operações de Crédito': 'Operaciones de Crédito',
    'Impostos, Taxas e Contribuições de Melhoria': 'Impuestos, Tasas y Contribuciones de Mejora',
    'Sem informação': 'Desconocido',
    'Amortizações de Empréstimos': 'Amortizaciones de Préstamos',
    'Contribuições': 'Contribuciones',
    'Receita Industrial': 'Ingresos Industriales',
    'Outras Receitas de Capital': 'Otros Ingresos de Capital',
    'Receitas Correntes - a classificar': 'Ingresos Corrientes - a clasificar',
    'Sem informação': 'Sin información'
    }


dicc_tipo_ingreso = {
    'Bens, Direitos e Valores Incorporados ao Patr': 'Bienes, Derechos y Valores Incorporados al Patrimonio',
    'Indenizações, restituições e ressarcimentos': 'Indemnizaciones, devoluciones y reembolsos',
    'Multas administrativas, contratuais e judicia': 'Multas administrativas, contractuales y judiciales',
    'Demais receitas correntes': 'Otros ingresos corrientes',
    'Receita de Serviços': 'Ingresos por Servicios',
    'Transferências de Instituições Privadas': 'Transferencias de Instituciones Privadas',
    'Alienação de bens móveis': 'Venta de bienes muebles',
    'Receita da produção animal e derivados': 'Ingresos de la producción animal y derivados',
    'Transferências dos Municípios e de suas Entid': 'Transferencias de los Municipios y sus Entidades',
    'Alienação de bens imóveis': 'Venta de bienes inmuebles',
    'Transferências de Pessoas Físicas': 'Transferencias de Personas Físicas',
    'Valores Mobiliários': 'Valores Mobiliarios',
    'Exploração do patrimônio imobiliário do Estad': 'Explotación del patrimonio inmobiliario del Estado',
    'Operações de crédito - mercado interno': 'Operaciones de crédito - mercado interno',
    'Taxas': 'Tasas',
    'Delegação de Serviços Públicos Mediante Conce': 'Delegación de Servicios Públicos Mediante Concesión',
    'Outras receitas agropecuárias': 'Otros ingresos agropecuarios',
    'Amortizações de Empréstimos': 'Amortizaciones de Préstamos',
    'Contribuições econômicas': 'Contribuciones económicas',
    'Transferências de Convênios': 'Transferencias de Convenios',
    'Indenizações e restituições': 'Indemnizaciones y devoluciones',
    'Receitas da indústria de transformação': 'Ingresos de la industria de transformación',
    'Contribuições sociais': 'Contribuciones sociales',
    'Receita dívida ativa alienação de estoques de': 'Ingresos de deuda activa por venta de existencias de',
    'Receita da produção vegetal': 'Ingresos de la producción vegetal',
    'Receita dívida ativa proveniente de amortizaç': 'Ingresos de deuda activa provenientes de amortización de',
    'Exploração de recursos naturais': 'Explotación de recursos naturales',
    'Receitas Correntes - a classificar': 'Ingresos Corrientes - a clasificar',
    'Receita de concessões e permissões': 'Ingresos de concesiones y permisos',
    'Demais receitas patrimoniais': 'Otros ingresos patrimoniales',
    'Cessão de direitos': 'Cesión de derechos',
    'Transferências de Outras Instituições Pública': 'Transferencias de Otras Instituciones Públicas',
    'Operações de crédito - mercado externo': 'Operaciones de crédito - mercado externo',
    'Impostos': 'Impuestos',
    'Resultado do Banco Central do Brasil': 'Resultado del Banco Central de Brasil',
    'Receitas decorrentes de aportes periódicos pa': 'Ingresos provenientes de aportes periódicos para',
    'Sem informação': 'Sin información',
    'Receitas de valores mobiliários': 'Ingresos de valores mobiliarios',
    'Receitas decorrentes de compensações ao Regim': 'Ingresos provenientes de compensaciones al Régimen',
    'Receita títulos do tesouro nacional resgatado': 'Ingresos de títulos del tesoro nacional rescatados',
    'Remuneração das Disponibilidades do Tesouro N': 'Remuneración de las Disponibilidades del Tesoro Nacional',
    'Outras receitas': 'Otros ingresos',
    'Transferências do Exterior': 'Transferencias del Exterior',
    'Transferências dos Estados e do Distrito Fede': 'Transferencias de los Estados y del Distrito Federal',
    'Integralização do capital social': 'Integralización del capital social',
    'Receita da dívida ativa': 'Ingresos de deuda activa',
    'Serviços Administrativos e Comerciais Gerais': 'Servicios Administrativos y Comerciales Generales',
    'Outros serviços': 'Otros servicios',
    'Receita Agropecuária': 'Ingresos Agropecuarios',
    'Transferências Correntes': 'Transferencias Corrientes',
    'Transferências da União e de suas Entidades': 'Transferencias de la Unión y sus Entidades',
    'Receita Industrial': 'Ingresos Industriales',
    'Serviços e Atividades Financeiras': 'Servicios y Actividades Financieras',
    'Transferências de Capital': 'Transferencias de Capital',
    'Serviços e Atividades Referentes à Saúde': 'Servicios y Actividades Relacionadas con la Salud',
    'Serviços e Atividades Referentes à Navegação': 'Servicios y Actividades Relacionadas con la Navegación',
    'Remuneração das Disponibilidades do Tesouro': 'Remuneración de las Disponibilidades del Tesoro',
    'Contribuições para Entidades Privadas de Serv': 'Contribuciones para Entidades Privadas de Servicios',
    'Alienação de bens intangíveis': 'Venta de bienes intangibles',
    'Resgate de Títulos do Tesouro': 'Rescate de Títulos del Tesoro',
    'Exploração do patrimônio intangível': 'Explotación del patrimonio intangible',
    'Transferências Provenientes de Depósito Não I': 'Transferencias Provenientes de Depósito No Identificado',
    'Demais receitas de capital': 'Otros ingresos de capital'
    }

